distancia = float(input('Digite a distancia em metros: '))
print(f'{distancia / 1000}km')
print(f'{distancia * 10}dm')
print(f'{distancia / 100}hm')
print(f'{distancia * 100}cm')
print(f'{distancia / 10}dam')
print(f'{distancia * 1000}')